sonar.projectKey=vitaly-zdanevich_youta
sonar.organization=vitaly-zdanevich
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests
sonar.rust.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=target/**,coverage/**
